# Definition of ROS service LocStart for sick localization.
#
# ROS service LocStart starts localization
# by sending cola command ("sMN LocStart").
#
# See Telegram-Listing-v1.1.0.241R.pdf for further details about 
# Cola telegrams and this command.

#
# Request (input)
#

---

#
# Response (output)
#

bool success # true: success response received from LLS device (localization started), false: service failed (timeout or error status from controller)

