# Definition of ROS service LocStop for sick localization.
#
# ROS service LocStop stops localization
# by sending cola command ("sMN LocStop").
#
# See Telegram-Listing-v1.1.0.241R.pdf for further details about
# Cola telegrams and this command.

#
# Request (input)
#

---

#
# Response (output)
#

bool success # true: success response received from LLS device, false: service failed (timeout or error status from controller)

